# Generated by Django 3.0.3 on 2020-02-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
