# Generated by Django 3.0.3 on 2020-02-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
