# Generated by Django 3.0.5 on 2020-04-11 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20200408_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist2',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist3',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_cart', models.CharField(default='', max_length=100000)),
                ('save_for_later', models.CharField(default='', max_length=100000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
