# Generated by Django 3.0.5 on 2020-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_auto_20200411_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='save_for_later',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopping_cart',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist2',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist3',
            field=models.CharField(max_length=100000),
        ),
    ]
