# Generated by Django 3.0.3 on 2020-02-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0005_remove_book_img_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_published',
            new_name='date_published',
        ),
    ]
