# Generated by Django 3.0.3 on 2020-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0007_auto_20200224_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
