# Generated by Django 3.0.5 on 2020-04-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0009_auto_20200227_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1970, max_length=4),
            preserve_default=False,
        ),
    ]
