# Generated by Django 3.0.5 on 2020-04-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0010_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
    ]
