# Generated by Django 3.0.3 on 2020-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0002_auto_20200218_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_bio',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
