# Generated by Django 3.0.3 on 2020-02-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0003_auto_20200222_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_ref',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
