# Generated by Django 3.0.3 on 2020-02-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0004_book_img_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img_ref',
        ),
    ]
