# Generated by Django 3.0.3 on 2020-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0006_auto_20200224_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
