# Generated by Django 3.0.2 on 2020-02-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0007_auto_20200224_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='price',
        ),
    ]
